import { FieldType } from '../enums/FieldType';
import { generateRandomString } from 'lkt-string-tools';
import { MultipleDisplayType } from '../enums/MultipleDisplayType';

export const LktFieldConfigDefaults = {
    modelValue: '',
    type: FieldType.Text,
    placeholder: '',
    searchPlaceholder: '',
    label: '',
    palette: '',
    name: generateRandomString(16),
    valid: false,
    autocomplete: true,
    disabled: false,
    readonly: false,
    readMode: false,
    allowReadModeSwitch: false,
    tabindex: undefined,
    mandatory: false,
    showPassword: false,
    canClear: false,
    canStep: true,
    mandatoryMessage: '',
    infoMessage: '',
    errorMessage: '',
    min: undefined,
    max: undefined,
    step: 1,
    enableAutoNumberFix: true,
    emptyValueSlot: '',
    valueSlot: '',
    editSlot: '',
    slotData: () => ({}),
    resource: '',
    resourceData: () => ({}),
    validationResource: '',
    validationResourceData: () => ({}),
    autoValidation: false,
    autoValidationType: 'blur',
    validationStack: 'default',
    minNumbers: undefined,
    maxNumbers: undefined,
    minChars: undefined,
    maxChars: undefined,
    minUpperChars: undefined,
    maxUpperChars: undefined,
    minLowerChars: undefined,
    maxLowerChars: undefined,
    minSpecialChars: undefined,
    maxSpecialChars: undefined,
    checkEqualTo: undefined,
    featuredButton: '',
    infoButtonEllipsis: false,
    fileName: '',
    options: () => [],
    multiple: false,
    multipleDisplay: MultipleDisplayType.List,
    multipleDisplayEdition: MultipleDisplayType.Inline,
    searchable: false,
    autoloadOptionsResource: false,
    optionsDownload: '',
    optionsModal: '',
    optionsModalData: () => ({}),
    optionsIcon: '',
    optionsResource: '',
    optionsResourceData: () => ({}),
    icon: '',
    modal: '',
    modalKey: '',
    modalData: () => ({}),
}